---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gol-deploy
    spec:
      minReadySeconds: 10
      replicas: 3
      selector:
        matchLabels:
          app: gameoflife
          ver: 1.0.0
      strategy:
        rollingUpdate:
          maxSurge: 35%
          maxUnavailable: 30%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: gameoflife
            ver: 1.0.0
        spec:
          containers:
            - name: gameoflife
              image: gkiran04/gameoflife:1.0.0
              ports:
                - containerPort: 8080
                  protocol: TCP
    